# **AI and ML Program by letsUpgrade**
# **DAY10 ASSIGNMENT**
# **SUBMITTED BY**
# **NAME:-PAIDIMARRI VENKATA SAI ASWITHA**

# **Question1**
# Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [2]:
import numpy as np
a=np.array([2,3,4,5])
b=np.array([6,2,4,1])
print("Comparison - greater")
print(np.greater(a,b))
print("Comparison - greater_equal")
print(np.greater_equal(a,b))
print("Comparison - less")
print(np.less(a,b))
print("Comparison - less_equal")
print(np.less_equal(a,b))

Comparison - greater
[False  True False  True]
Comparison - greater_equal
[False  True  True  True]
Comparison - less
[ True False False False]
Comparison - less_equal
[ True False  True False]


# **Question2**
# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [7]:
import numpy as np
a=np.zeros(10)
b=np.ones(10)
c=np.ones(10)*5
print("array of 10 zeros:",a)
print("array of 10 ones:",b)
print("array of 10 zeros:",c)

array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 zeros: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# **Question3**
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array 

In [16]:
import numpy as np
a=np.array([[2,3,4,5],[1,2,4,7]])
print("Original array:")
print(a)
print("Sum of all elements:")
print(np.sum(a))
print("Sum of each column:")
print(np.sum(a,axis=0))
print("Sum of each row:")
print(np.sum(a,axis=1))

Original array:
[[2 3 4 5]
 [1 2 4 7]]
Sum of all elements:
28
Sum of each column:
[ 3  5  8 12]
Sum of each row:
[14 14]


# **Question4**
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [11]:
import numpy as np
print("Add:")
print(np.add(1, 4))
print("Subtract:")
print(np.subtract(1, 4))
print("Multiply:")
print(np.multiply(1, 4))
print("Divide:")
print(np.divide(1, 4))


Add:
5
Subtract:
-3
Multiply:
4
Divide:
0.25


# **Question5**
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [17]:
import numpy as np
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# Question6
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [38]:
import pandas as pd
import numpy as np
data={"Names":["Aswitha","Hasini","Navya","Vidya","Chikki"],
      "Id":[100,230,123,234,270],
      "Company":["Infosys","wipro","Tcs","cognigent","capgemini"],
      "Salary in K":[3.3,3.5,4.0,2.3,2.2]}
labels=[1,2,3,4,5]
df = pd.DataFrame(data,index=labels)
print(df)

     Names   Id    Company  Salary in K
1  Aswitha  100    Infosys          3.3
2   Hasini  230      wipro          3.5
3    Navya  123        Tcs          4.0
4    Vidya  234  cognigent          2.3
5   Chikki  270  capgemini          2.2
